title: Cable Spark
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
palette: blue
header:
  title: Azimuth
  logo_img: images/logo.jpeg
  has_nav: true
  nav_links:
    - label: Home
      url: /
    - label: About Us
      url: /about
    - label: Why Choose us
      url: /pricing
    - label: Services
      url: /blog
    - label: Contact Us
      url: /contact
      primary: true
footer:
  logo_img: images/logo.jpeg
  tagline: Cable Spark @ 2017
  has_nav: true
  nav_title: Company
  nav_links:
    - label: About Us
      url: /about
    - label: Why Choose Us
      url: /blog
    - label: Services
      url: /pricing
    - label: Contact
      url: /contact
  has_social: true
  social_title: Community
  social_links:
    - label: Twitter
      url: 'https://twitter.com/'
      new_window: true
    - label: Instagram
      url: 'https://www.instagram.com/'
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      new_window: true
  has_subscribe: true
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our latest developments.
  content: '&copy; Stackbit. All rights reserved.'
  links:
    - label: Made with Stackbit
      url: 'https://www.stackbit.com'
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
